
 const DestinationsData = [
    {
        id: '1',
        name: 'Hawaii, USA',
        type: 'trip',
        price: 1300,
        image: 'https://media.istockphoto.com/photos/aerial-view-of-kualoa-area-of-oahu-hawaii-picture-id938335974?k=20&m=938335974&s=612x612&w=0&h=0pYDh3iR4ZPrnL6Kdc0LdibcAyyvdXm4ElD8KvOp2DY=',
        time: '13 Days, 12 Nights',
    },
    {
        id: '2',
        name: 'Hanoi, Vietnam',
        type: 'trip',
        price:  3300,
        image: 'https://www.travelanddestinations.com/wp-content/uploads/2019/10/Ban-Gioc-Detian-Waterfalls-Vietnam-1.jpg',
        time: '13 Days, 12 Nights',
    },
    {
        id: '3',
        name: 'Kuala, Lumpur',
        type: 'trip',
        price: 2640,
        image: 'https://www.planetware.com/wpimages/2019/10/malaysia-best-places-to-visit-kuala-lumpur.jpg',
        time: '13 Days, 12 Nights',
    },
    {
        id: '4',
        name: 'Bali, Indonesia',
        type: 'trip',
        price: 2200,
        image: 'https://www.ttrweekly.com/site/wp-content/uploads/2019/02/bali-indonesia-2.jpg',
        time: '13 Days, 12 Nights',
    },
    {
        id: '5',
        name: 'Galapagos, Ecuador',
        type: 'trip',
        price: 1300,
        image: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F28%2F2019%2F12%2Fgalapagos-islands-ecuador-GALAPA1104.jpg&q=85',
        time: '13 Days, 12 Nights',
    },
    {
        id: '6',
        name: 'Chichen Itza, Mexico',
        type: 'hiking',
        price: 800,
        image: 'https://img.itinari.com/pages/images/original/c2bd2f41-9cb2-4b12-98f1-0cdad06f35a6-istock-481272289.jpg?ch=DPR&dpr=1&w=1600&s=4d500971e1c2dfd26acf4bf3511280e2',
        time: '13 Days, 12 Nights',
    },
    {
        id: '7',
        name: 'Machiu Piciu, Peru',
        type: 'hiking',
        price: 1600,
        image: 'https://www.europafm.ro/wp-content/uploads/2017/01/Machu-Picchu.jpg',
        time: '13 Days, 12 Nights',
    },
    {
        id: '8',
        name: 'Sydney, Australia',
        type: 'trip',
        price: 2500,
        image: 'https://www.umultirank.org/export/sites/default/.galleries/generic-images/Others/Winter-Calendar/why-should-I-study-in-Sydney.jpg_1079324579.jpg',
        time: '13 Days, 12 Nights',
    },
    {
        id: '9',
        name: 'Los Angeles, USA',
        type: 'trip',
        price: 1780,
        image: 'https://media.timeout.com/images/105718842/750/562/image.jpg',
        time: '13 Days, 12 Nights',
    }, 
    {
        id: '10',
        name: 'Flores Island, Indonesia',
        type: 'beach',
        price: 2180,
        image: 'https://www.cruisemapper.com/images/ports/1148-5fd82dbaf6f.jpg',
        time: '13 Days, 12 Nights',
    }, 
    {
        id: '11',
        name: 'Phuket, Thailand',
        type: 'trip',
        price: 1500,
        image: 'https://www.telegraph.co.uk/content/dam/Travel/Destinations/Asia/Thailand/Phuket/phuket-thailand-beach-boat-lead-main-guide-xlarge.jpg',
        time: '9 Days, 8 Nights',
    }, 
    {
        id: '12',
        name: 'Bolzano, Italy',
        type: 'mountains',
        price: 900,
        image: 'https://files.tripstodiscover.com/files/2015/07/Lake-Oeschinen.jpg',
        time: '7 Days, 6 Nights',
    }, 
    {
        id: '13',
        name: 'Bondi Beach, Australia',
        type: 'beach',
        price: 3150,
        image: 'https://i.pinimg.com/originals/4b/40/19/4b4019a05ada729566ecfc432909ff18.jpg',
        time: '8 Days, 7 Nights',
    }, 
    {
        id: '14',
        name: 'Berna, Switerland',
        type: 'mountains',
        price: 1450,
        image: 'https://files.tripstodiscover.com/files/2015/07/Lake-Oeschinen.jpg',
        time: '13 Days, 12 Nights',
    }, 
    {
        id: '15',
        name: 'Tokyo, Japan',
        type: 'trip',
        price: 4200,
        image: 'https://d1ix9yerv4y8lr.cloudfront.net/blog/wp-content/uploads/2019/07/tokyo-ops-7-19-750x375.jpg',
        time: '13 Days, 12 Nights',
    }, 
    {
        id: '16',
        name: 'Seoul, South Koreea',
        type: 'trip',
        price: 1890,
        image: 'https://www.lowyinstitute.org/sites/default/files/GettyImages-1134201090.jpeg',
        time: '13 Days, 12 Nights',
    }, 
]

export default DestinationsData;